# Generated by Django 4.2 on 2023-04-21 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="blog_thumbnails/"),
        ),
        migrations.AlterUniqueTogether(
            name="blog",
            unique_together={("author", "title")},
        ),
    ]
