# Generated by Django 4.2 on 2023-04-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_slug_alter_blog_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
    ]
