# Generated by Django 4.2 on 2023-05-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_blogstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogstats",
            name="comments_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
