# Generated by Django 4.2 on 2023-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_blogstats_comments_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogstats",
            name="comments_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
